import { Role, Permission } from '../types/auth';

export const ROLES: Record<string, Role> = {
  GUEST: 'guest',
  CLIENT: 'client',
  SUPPORT: 'support',
  SALES: 'sales',
  DEVELOPER: 'developer',
  AI_OPERATOR: 'ai_operator',
  HR: 'hr',
  FINANCE: 'finance',
  PROJECT_MANAGER: 'project_manager',
  OPERATIONS: 'operations',
  TENANT_ADMIN: 'tenant_admin',
  PLATFORM_OWNER: 'platform_owner',
  SUPER_ADMIN: 'super_admin',
};

export const ROLE_HIERARCHY: Role[] = [
  ROLES.GUEST,
  ROLES.CLIENT,
  ROLES.SUPPORT,
  ROLES.SALES,
  ROLES.DEVELOPER,
  ROLES.AI_OPERATOR,
  ROLES.HR,
  ROLES.FINANCE,
  ROLES.PROJECT_MANAGER,
  ROLES.OPERATIONS,
  ROLES.TENANT_ADMIN,
  ROLES.PLATFORM_OWNER,
  ROLES.SUPER_ADMIN,
];

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'dashboard.view' as Permission,
  CUSTOMIZE_DASHBOARD: 'dashboard.customize' as Permission,

  VIEW_LEADS: 'leads.view' as Permission,
  CREATE_LEADS: 'leads.create' as Permission,
  EDIT_LEADS: 'leads.edit' as Permission,
  DELETE_LEADS: 'leads.delete' as Permission,
  ASSIGN_LEADS: 'leads.assign' as Permission,
  EXPORT_LEADS: 'leads.export' as Permission,

  VIEW_CONTACTS: 'contacts.view' as Permission,
  CREATE_CONTACTS: 'contacts.create' as Permission,
  EDIT_CONTACTS: 'contacts.edit' as Permission,
  DELETE_CONTACTS: 'contacts.delete' as Permission,

  VIEW_PIPELINE: 'pipeline.view' as Permission,
  EDIT_PIPELINE: 'pipeline.edit' as Permission,
  MANAGE_PIPELINE_STAGES: 'pipeline.manage_stages' as Permission,

  VIEW_CLIENTS: 'clients.view' as Permission,
  CREATE_CLIENTS: 'clients.create' as Permission,
  EDIT_CLIENTS: 'clients.edit' as Permission,
  DELETE_CLIENTS: 'clients.delete' as Permission,

  VIEW_PROJECTS: 'projects.view' as Permission,
  CREATE_PROJECTS: 'projects.create' as Permission,
  EDIT_PROJECTS: 'projects.edit' as Permission,
  DELETE_PROJECTS: 'projects.delete' as Permission,
  MANAGE_PROJECT_TEAM: 'projects.manage_team' as Permission,

  VIEW_BILLING: 'billing.view' as Permission,
  CREATE_INVOICE: 'billing.create_invoice' as Permission,
  EDIT_INVOICE: 'billing.edit_invoice' as Permission,
  DELETE_INVOICE: 'billing.delete_invoice' as Permission,
  MANAGE_SUBSCRIPTIONS: 'billing.manage_subscriptions' as Permission,

  VIEW_CONTRACTS: 'contracts.view' as Permission,
  CREATE_CONTRACTS: 'contracts.create' as Permission,
  SEND_CONTRACTS: 'contracts.send' as Permission,
  DELETE_CONTRACTS: 'contracts.delete' as Permission,

  VIEW_SUPPORT: 'support.view' as Permission,
  MANAGE_SUPPORT: 'support.manage' as Permission,
  ASSIGN_SUPPORT: 'support.assign' as Permission,

  VIEW_ANALYTICS: 'analytics.view' as Permission,
  EXPORT_ANALYTICS: 'analytics.export' as Permission,
  EXECUTIVE_ANALYTICS: 'analytics.executive' as Permission,

  AI_CHAT: 'ai.chat' as Permission,
  AI_GENERATE: 'ai.generate' as Permission,
  AI_ADMIN: 'ai.admin' as Permission,

  VIEW_TEAM: 'team.view' as Permission,
  MANAGE_TEAM: 'team.manage' as Permission,
  INVITE_TEAM: 'team.invite' as Permission,

  VIEW_AUDIT: 'audit.view' as Permission,
  EXPORT_AUDIT: 'audit.export' as Permission,

  VIEW_AUTOMATIONS: 'automations.view' as Permission,
  CREATE_AUTOMATIONS: 'automations.create' as Permission,
  DELETE_AUTOMATIONS: 'automations.delete' as Permission,

  VIEW_SETTINGS: 'settings.view' as Permission,
  TENANT_SETTINGS: 'settings.tenant' as Permission,
  SECURITY_SETTINGS: 'settings.security' as Permission,
  BILLING_ADMIN_SETTINGS: 'settings.billing_admin' as Permission,

  CLIENT_PORTAL_VIEW: 'client_portal.view' as Permission,
  CLIENT_PORTAL_INVOICES: 'client_portal.invoices' as Permission,
  CLIENT_PORTAL_CONTRACTS: 'client_portal.contracts' as Permission,
  CLIENT_PORTAL_PROJECTS: 'client_portal.projects' as Permission,
  CLIENT_PORTAL_SUPPORT: 'client_portal.support' as Permission,

  // ── Finance Module Permissions ───────────────────────────────────
  FINANCE_VIEW: 'finance.view' as Permission,
  FINANCE_CREATE: 'finance.create' as Permission,
  FINANCE_EDIT: 'finance.edit' as Permission,
  FINANCE_DELETE: 'finance.delete' as Permission,

  INVOICE_VIEW: 'invoice.view' as Permission,
  INVOICE_CREATE: 'invoice.create' as Permission,
  INVOICE_SEND: 'invoice.send' as Permission,
  INVOICE_APPROVE: 'invoice.approve' as Permission,

  PAYMENT_VIEW: 'payment.view' as Permission,
  PAYMENT_MANAGE: 'payment.manage' as Permission,
  PAYMENT_REFUND: 'payment.refund' as Permission,

  EXPENSE_VIEW: 'expense.view' as Permission,
  EXPENSE_SUBMIT: 'expense.submit' as Permission,
  EXPENSE_APPROVE: 'expense.approve' as Permission,

  BUDGET_VIEW: 'budget.view' as Permission,
  BUDGET_MANAGE: 'budget.manage' as Permission,

  REPORT_VIEW: 'report.view' as Permission,
  REPORT_EXPORT: 'report.export' as Permission,

  SUBSCRIPTION_MANAGE: 'subscription.manage' as Permission,

  VENDOR_VIEW: 'vendor.view' as Permission,
  VENDOR_MANAGE: 'vendor.manage' as Permission,

  // ── HR Module Permissions ────────────────────────────────────────
  HR_VIEW: 'hr.view' as Permission,
  HR_MANAGE: 'hr.manage' as Permission,
  HR_SELF_SERVICE: 'hr.self_service' as Permission,
};

export const PERMISSION_MATRIX: Record<Permission, Role[]> = {
  [PERMISSIONS.VIEW_DASHBOARD]: [
    ROLES.GUEST,
    ROLES.CLIENT,
    ROLES.SUPPORT,
    ROLES.SALES,
    ROLES.DEVELOPER,
    ROLES.AI_OPERATOR,
    ROLES.HR,
    ROLES.FINANCE,
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CUSTOMIZE_DASHBOARD]: [
    ROLES.SALES,
    ROLES.DEVELOPER,
    ROLES.AI_OPERATOR,
    ROLES.HR,
    ROLES.FINANCE,
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_LEADS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_LEADS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EDIT_LEADS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_LEADS]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.ASSIGN_LEADS]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXPORT_LEADS]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_CONTACTS]: [
    ROLES.SALES,
    ROLES.SUPPORT,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_CONTACTS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EDIT_CONTACTS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_CONTACTS]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_PIPELINE]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.FINANCE,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EDIT_PIPELINE]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.MANAGE_PIPELINE_STAGES]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_CLIENTS]: [
    ROLES.SALES,
    ROLES.SUPPORT,
    ROLES.OPERATIONS,
    ROLES.FINANCE,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_CLIENTS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EDIT_CLIENTS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_CLIENTS]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_PROJECTS]: [
    ROLES.DEVELOPER,
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_PROJECTS]: [
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EDIT_PROJECTS]: [
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_PROJECTS]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.MANAGE_PROJECT_TEAM]: [
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_BILLING]: [
    ROLES.FINANCE,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_INVOICE]: [
    ROLES.FINANCE,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EDIT_INVOICE]: [
    ROLES.FINANCE,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_INVOICE]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.MANAGE_SUBSCRIPTIONS]: [
    ROLES.FINANCE,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_CONTRACTS]: [
    ROLES.SALES,
    ROLES.FINANCE,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_CONTRACTS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.SEND_CONTRACTS]: [
    ROLES.SALES,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_CONTRACTS]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_SUPPORT]: [
    ROLES.SUPPORT,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.MANAGE_SUPPORT]: [
    ROLES.SUPPORT,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.ASSIGN_SUPPORT]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_ANALYTICS]: [
    ROLES.SALES,
    ROLES.FINANCE,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXPORT_ANALYTICS]: [
    ROLES.FINANCE,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXECUTIVE_ANALYTICS]: [
    ROLES.FINANCE,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.AI_CHAT]: [
    ROLES.SALES,
    ROLES.SUPPORT,
    ROLES.DEVELOPER,
    ROLES.AI_OPERATOR,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.AI_GENERATE]: [
    ROLES.SALES,
    ROLES.AI_OPERATOR,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.AI_ADMIN]: [
    ROLES.AI_OPERATOR,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_TEAM]: [
    ROLES.HR,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.MANAGE_TEAM]: [
    ROLES.HR,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.INVITE_TEAM]: [
    ROLES.HR,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_AUDIT]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXPORT_AUDIT]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_AUTOMATIONS]: [
    ROLES.OPERATIONS,
    ROLES.AI_OPERATOR,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.CREATE_AUTOMATIONS]: [
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.DELETE_AUTOMATIONS]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.VIEW_SETTINGS]: [
    ROLES.SALES,
    ROLES.SUPPORT,
    ROLES.DEVELOPER,
    ROLES.AI_OPERATOR,
    ROLES.HR,
    ROLES.FINANCE,
    ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS,
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.TENANT_SETTINGS]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.SECURITY_SETTINGS]: [
    ROLES.TENANT_ADMIN,
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.BILLING_ADMIN_SETTINGS]: [
    ROLES.PLATFORM_OWNER,
    ROLES.SUPER_ADMIN,
  ],

  [PERMISSIONS.CLIENT_PORTAL_VIEW]: [
    ROLES.CLIENT,
    ROLES.GUEST,
  ],
  [PERMISSIONS.CLIENT_PORTAL_INVOICES]: [
    ROLES.CLIENT,
  ],
  [PERMISSIONS.CLIENT_PORTAL_CONTRACTS]: [
    ROLES.CLIENT,
  ],
  [PERMISSIONS.CLIENT_PORTAL_PROJECTS]: [
    ROLES.CLIENT,
  ],
  [PERMISSIONS.CLIENT_PORTAL_SUPPORT]: [
    ROLES.CLIENT,
  ],

  // ── Finance Module Permission Matrix ─────────────────────────────
  [PERMISSIONS.FINANCE_VIEW]: [
    ROLES.FINANCE, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.FINANCE_CREATE]: [
    ROLES.FINANCE, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.FINANCE_EDIT]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.FINANCE_DELETE]: [
    ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.INVOICE_VIEW]: [
    ROLES.FINANCE, ROLES.SALES, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.INVOICE_CREATE]: [
    ROLES.FINANCE, ROLES.SALES, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.INVOICE_SEND]: [
    ROLES.FINANCE, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.INVOICE_APPROVE]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.PAYMENT_VIEW]: [
    ROLES.FINANCE, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.PAYMENT_MANAGE]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.PAYMENT_REFUND]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXPENSE_VIEW]: [
    ROLES.FINANCE, ROLES.HR, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXPENSE_SUBMIT]: [
    ROLES.SALES, ROLES.SUPPORT, ROLES.DEVELOPER, ROLES.HR, ROLES.FINANCE, ROLES.PROJECT_MANAGER,
    ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.EXPENSE_APPROVE]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.BUDGET_VIEW]: [
    ROLES.FINANCE, ROLES.PROJECT_MANAGER, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.BUDGET_MANAGE]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.REPORT_VIEW]: [
    ROLES.FINANCE, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.REPORT_EXPORT]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.SUBSCRIPTION_MANAGE]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.VENDOR_VIEW]: [
    ROLES.FINANCE, ROLES.OPERATIONS, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.VENDOR_MANAGE]: [
    ROLES.FINANCE, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.HR_VIEW]: [
    ROLES.HR, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.HR_MANAGE]: [
    ROLES.HR, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
  [PERMISSIONS.HR_SELF_SERVICE]: [
    // Everyone should probably have self service? Wait, "roles are given". So maybe just standard roles
    ROLES.HR, ROLES.FINANCE, ROLES.OPERATIONS, ROLES.SALES, ROLES.DEVELOPER, ROLES.SUPPORT, ROLES.AI_OPERATOR, ROLES.PROJECT_MANAGER, ROLES.TENANT_ADMIN, ROLES.PLATFORM_OWNER, ROLES.SUPER_ADMIN,
  ],
} as Record<Permission, Role[]>;
